#!/bin/bash

xrandr --output DP-1 --off --output DP-2 --primary --mode 3440x1440 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-3 --mode 2560x1440 --pos 371x1440 --rotate normal

notify-send "Cintiq display connected"

feh --bg-fill --randomize ~/Pictures/wallpapers/* &

sleep 5

notify-send "Cintiq settings applied"

# Define tablet name
TABLET_NAME="Wacom Cintiq Pro 16"

# Define full device names
STYLUS="$TABLET_NAME Pen stylus"
PAD="$TABLET_NAME Pad pad"
TOUCH="$TABLET_NAME Touch Finger touch"
ERASER="$TABLET_NAME Pen eraser"

# Set mapping to a specific monitor
xsetwacom set "$STYLUS" MapToOutput DP-3
xsetwacom set "$ERASER" MapToOutput DP-3
xsetwacom set "$TOUCH" MapToOutput DP-3
xsetwacom set "$PAD" MapToOutput DP-3

# Turn tablet's touch settings off
xsetwacom set "$TOUCH" Touch "off"

# Rotate tablet for left-handed use
xsetwacom set "$STYLUS" Rotate "none"

# Pen Buttons
xsetwacom set "$STYLUS" Button 1 "button +1" # Pen tip (draw - don't edit)
xsetwacom set "$STYLUS" Button 2 "button +1" # Right Click (draw)
xsetwacom set "$STYLUS" Button 3 "button +2" # Middle Click (move canvas)

# Set mode to relative (like a mouse) or absolute (like a pen)
xsetwacom set "$STYLUS" Mode "Absolute"

# Sets if the stylus needs to touch the tablet for the pen's buttons to work
xsetwacom set "$STYLUS" TabletPCButton "on"

# Print confirmation
echo "Tablet settings applied for $TABLET_NAME"
