#!/bin/bash

xrandr --output DP-1 --off --output DP-2 --primary --mode 3440x1440 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-3 --off

#feh --bg-fill --randomize ~/Pictures/wallpapers/* &
