#!/usr/bin/env bash

HOME_DIR="/home/tristen"

# In .config
ln -sf "$HOME_DIR/Projects/dotfiles/config/mpv" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/dunst" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/picom" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/nvim" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/gtk-3.0" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/gtk-4.0" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/pcmanfm" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/qalculate" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/zathura" "$HOME_DIR/.config/"
ln -sf "$HOME_DIR/Projects/dotfiles/config/user-dirs.dirs" "$HOME_DIR/.config/"

# In home directory
ln -sf "$HOME_DIR/Projects/dotfiles/laptop_dot_xinitrc" "$HOME_DIR/.xinitrc"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_bashrc" "$HOME_DIR/.bashrc"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_bash_profile" "$HOME_DIR/.bash_profile"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_xprofile" "$HOME_DIR/.xprofile"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_gitconfig" "$HOME_DIR/.gitconfig"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_gtk-bookmarks" "$HOME_DIR/.gtk-bookmarks"
ln -sf "$HOME_DIR/Projects/dotfiles/dot_gtkrc-2.0" "$HOME_DIR/.gtkrc-2.0"

# Telekasten NeoVim Plugin Templates
ln -sf "$HOME_DIR/Projects/dotfiles/telekasten-nvim/templates" "$HOME_DIR/Documents/notes"

# .Desktop files
cp "$HOME_DIR/Projects/dotfiles/dot-desktop/nsxiv.desktop" "/usr/share/applications/"
