#!/bin/sh

# Copied from Luke Smith - https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar

filter() {
	mpc status | awk '
	NR==1 { song=$0 }
	NR==2 {
		icon="▶"
		if ($0 ~ /\[paused\]/) icon="⏸"
		if ($0 ~ /\[stopped\]/) icon="⏹"
		print icon " " song
	}'
}

pidof -x sb-mpdup >/dev/null 2>&1 || sb-mpdup >/dev/null 2>&1 &

case "$BLOCK_BUTTON" in
	1) mpc toggle ;;
	2) mpc prev ;;
	3) mpc next ;;
esac

mpc status | filter | paste -sd ' ' -
